version: "3"
services:
  front:
    build:
      context: ./frontend
      args:
        - ISCNF
    environment:
      API_HOST: "back"
      API_PORT: "9090"
    ports:
      - "9091:9091"
    depends_on:
      - back
  back:
    build:
      context: ./backend
      args:
        - ISCNF
    environment:
      DB_HOST: "host.docker.internal"
      DB_PORT: "3306"
    ports:
      - "9090:9090"
